### PR TITLE
WE'RE SO BACK!

### PR DESCRIPTION
**Pull request by ZakaHaceCosas**
btw draft PR because there's stuff TODO yet (it's 11pm alright?)

TODO
- [X] update vuelto's logo everywhere
- [X] the website says "licensed under GPL", thats not correct
- [ ] update docs to be complete

### CODE REVIEW

**Comment by dimkauzh** [comment]
This is damn crazy bro, good job. Can't wait until this shit is fully cooked 🔥

**Comment by ZakaHaceCosas** [comment]
okay yeah unexpected things happened and i won't have time to fully polish this
the post said we would _SOON_ have full docs anyway so yeah, i'll slowly work on the documentation
that said, i think this is ready for review

**Comment by dimkauzh** [comment]
Ready for merging :)

**Comment by dimkauzh** [comment]
Only 2 files left

**Pull request merged**
